#!/usr/bin/env sh

set -eu

root="$(git rev-parse --show-toplevel)"
cache=$(go env GOMODCACHE)

# Scrape packages.
gomod="${root}/go.mod"
packages=$(sed -n '/^\t/,//{ s|\t\(\S\+\)\ \(v\S\+\).*\?|\1\@\2|;p }' "$gomod")

# Make output directory.
content="${root}/web/docs/licenses"
mkdir -p "$content"

# Scrape licenses.
for package in $packages; do
    name=$(echo "$package" | tr '[:upper:]' '[:lower:]')
    package=$(echo "$package" | sed 's|\([A-Z]\)|!\L\1|g')
    path="${content}/$(echo "${name%@*}" | sed 's|/|-|g').txt"

    for f in "license" "license.*" "copying"; do
        if find "$cache/$package" -iname "$f" -exec cp -f {} "$path" \;; then
            if [ -f "$path" ]; then
                printf "* [%s](/license/%s)\n" "$name" "${path##*/}"
                break
            fi
        fi
    done
done
