"""
This script generates the license documentation pages.
"""

from os import system, getcwd, listdir, chmod, rename
from os.path import dirname, basename

# Directory where the scraped licenses are.
Dir = dirname(__file__) + "/../web/"

# copy licenses from customlicenses
Licenses = listdir(Dir + "customlicenses")
for License in Licenses:
	system("cp " + Dir + "customlicenses/" + License + " " + Dir + "docs/licenses/" + License)
Dir += "docs/licenses"

# where licenses will be linked
IndexPath = Dir + ".md"
IndexText = ""

# list licenses generated by licenser and go through them
Licenses = listdir(Dir)
for License in Licenses:
	Path = Dir + "/" + License

	# make files writeable
	chmod(Path, 0o0600)

	with open(Path, "r") as File:
		# trim, enclose as codeblock
		TheText = "```\n" + File.read().strip() + "\n```"

	# use filename as license name, remove host prefix
	Name = License.partition("-")[2].rpartition(".txt")[0]
	RelName = Name
	Name += " license"

	# generate document
	Text = "---\n" + "Title: "+ Name + "\n---\n# " + Name
	Text += "\n\n[Back to licenses](/docs/licenses)\n\n"
	Text += "\n" + TheText

	if RelName == "stylus-logo":
		Text += "\n\n\n#### Changes:\n- vectorized by [pabli24](https://github.com/pabli24)\n- converted to monochrome outline by [0eoc](https://userstyles.world/user/0eoc)"

	# write license as document
	with open(Path, "w") as File:
		File.write(Text)

	# rename file
	rename(Path, Dir + "/" + RelName + ".md")

	# add license link to index
	IndexText += "\n- [" + RelName + "](/docs/licenses/" + RelName + ")\n"

# write license index. we could write to it on every license but i prefer writing big chunks
with open(IndexPath, "w") as IndexFile:
	IndexFile.write("---\nTitle: Third-party Licenses\n---\n# Third-party Licenses\n" + IndexText)
