#!/usr/bin/env sh

set -xe

log() { printf "%s %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$@"; }

gen() {
    vips webpsave "$1" "$2.webp" --strip --reduction-effort 4 --Q 80
    vips jpegsave "$1" "$2.jpeg" --strip --Q 80 --optimize-coding
    vipsthumbnail "$2.webp" --size 300 -o '%st.webp[profile=none]'
    vipsthumbnail "$2.jpeg" --size 300 -o '%st.jpeg[profile=none]'
    log "Generated images for style ${1%.original}"
}

root="$(git rev-parse --show-toplevel)"
images="$root/data/images"
public="$root/data/public"

cd "$images"

batch=10
count=0
for i in *.original; do
    count=$(( count + 1 ))

    # Set up output directory.
    out="${public}/${i%.original}"
    mkdir -p "$out"

    # Process images in a subshell.
    gen "$i" "${out}/0" &

    # Process images in batches.
    [ $(( count % batch )) = 0 ] && sleep 1
done

# Wait for all subshells to finish.
wait

# Remove empty directories from broken images.
find "$public" -type d -empty -delete
