#!/usr/bin/env sh

data="data-thumbs.txt"

log() { printf "%s\n" "$@"; }

scrape() {
    log "Scraping images..."

    grep -h "preview" ../content/userstyle/*md | awk '{ print $2 }' > "$data"

    log "Done!"
}

download() {
    log "Downloading images..."

    mkdir -p data-images

    while read -r line; do
        # Remove `https://` then replace all `/` with `_` so that the downloaded
        # image can be saved in the data-images directory.
        # TODO: Implement a comparsion to avoid re-downloading images.
        sanitized=$( printf "%s" "$line" | sed -e 's/https\?:\/\///g; s/\//_/g' )

        curl -# \
            -o "data-images/$sanitized" \
            -L "$line"
    done < "$data"

    log "Done!"
}

resize() {
    log "Making thumbnails..."

    mkdir -p data-thumbs

    for f in data-images/*png; do
        output=${f##data-images/}
        printf "I: %s\nO: %s\n\n" "$f" "data-thumbs/$output"
        convert "$f" -resize 460x260 "data-thumbs/$output"
    done

    log "Done!"
}

clean() {
    log "Cleaning files..."

    rm -r data-images data-thumbs "$data"

    log "Done!"
}

all() {
    scrape
    log ""
    download
    log ""
    resize
}

case "$1" in
    h|help) printf "See the source code.\n" ;;
    g|rg|grep|scrape) scrape "$@" ;;
    d|dl|download) download "$@" ;;
    r|resize) resize "$@" ;;
    c|clean) clean "$@" ;;
    a|all) all "$@" ;;
    *) printf "Invalid option: %s\n" "$*" ;;
esac
